version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
            - "8443:1443"
        volumes:
            - ./src:/var/www/html
            - ./certs:/ncerts
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        networks:
            - back
            - front

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html
        networks:
            - back

networks:
  back:
    internal: true
  front:
    external: true